targets:
  $default:
    builders:
      mobx_codegen|mobx_generator:
        enabled: true
        generate_for:
          include:
            - lib/**/*_controller.dart
            - lib/**/*_store.dart
