name: prodea
description: Aplicativo do Projeto Integrador UNIVESP.

publish_to: "none"

version: 2.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^1.21.1
  firebase_storage: ^10.3.7
  firebase_auth: ^3.7.0
  cloud_firestore: ^3.4.6

  # Utils
  uuid: ^3.0.6
  flutter_svg: ^1.1.4
  intl: ^0.17.0
  mask_text_input_formatter: ^2.4.0
  diacritic: ^0.1.3
  equatable: ^2.0.5
  asuka: ^2.0.1

  # Platform Tools
  connectivity_plus: ^2.3.6+1
  image_picker: ^0.8.5+3
  image_picker_for_web: ^2.1.10
  flutter_native_splash: ^2.2.9
  path_provider: ^2.0.11
  url_launcher: ^6.1.6

  # State Management
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1

  # DI and Navigation
  flutter_modular: ^5.0.3

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Tests
  mocktail: ^0.3.0
  modular_test: ^2.0.0

  # Firebase Tests
  fake_cloud_firestore: ^1.3.1
  firebase_storage_mocks: ^0.5.1

  # Platform Tools
  flutter_launcher_icons: ^0.10.0

  # Codegen
  mobx_codegen: ^2.0.7
  build_runner: ^2.2.0

  # Lints
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: "assets/icon.png"
  color: "#fffbff"
  color_dark: "#201b17"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  web:
    generate: true
  windows:
    generate: true
