// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFCV6zBADtP3oay-leJ5e00x_R3iqWjdY',
    appId: '1:258044886668:web:f874519946be2c8e3205a9',
    messagingSenderId: '258044886668',
    projectId: 'prodea-pi',
    authDomain: 'prodea-pi.firebaseapp.com',
    storageBucket: 'prodea-pi.appspot.com',
    measurementId: 'G-QJ6M8FZ31M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqPNN5-UC_Puht5XuYzzYnyxdVOr0jA18',
    appId: '1:258044886668:android:15f1fb58272f9e1a3205a9',
    messagingSenderId: '258044886668',
    projectId: 'prodea-pi',
    storageBucket: 'prodea-pi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkcNCyjY7MEG9Jek-d9TV1K9OgFtDAVM8',
    appId: '1:258044886668:ios:20069634b33cb8113205a9',
    messagingSenderId: '258044886668',
    projectId: 'prodea-pi',
    storageBucket: 'prodea-pi.appspot.com',
    iosClientId: '258044886668-gaubdaf7aamo1ugc3j7a2c5canncnphc.apps.googleusercontent.com',
    iosBundleId: 'com.example.prodea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkcNCyjY7MEG9Jek-d9TV1K9OgFtDAVM8',
    appId: '1:258044886668:ios:20069634b33cb8113205a9',
    messagingSenderId: '258044886668',
    projectId: 'prodea-pi',
    storageBucket: 'prodea-pi.appspot.com',
    iosClientId: '258044886668-gaubdaf7aamo1ugc3j7a2c5canncnphc.apps.googleusercontent.com',
    iosBundleId: 'com.example.prodea',
  );
}
