name: Flutter Tests and Merge Main Branch
on:
  push:
    branches:
      - dev

jobs:
  flutter-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v3

      # - name: Setup Java
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: "12.x"

      # - name: Setup Flutter SDK
      #   uses: subosito/flutter-action@v2
      #   with:
      #     channel: "stable"

      # - name: Run Flutter Pub Get
      #   run: flutter pub get

      # - name: Run Unit and Widget Tests
      #   run: flutter test test

  flutter-integration-tests:
    runs-on: ubuntu-latest
    needs: flutter-tests
    steps:
      - name: Get Repository
        uses: actions/checkout@v3

      # - name: Setup Java
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: "12.x"

      # - name: Setup Flutter SDK
      #   uses: subosito/flutter-action@v2
      #   with:
      #     channel: "stable"

      # - name: Run Flutter Pub Get
      #   run: flutter pub get

      # - name: Google Cloud Auth
      #   uses: google-github-actions/auth@v0
      #   with:
      #     credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      # - name: Setup Google Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v0

      # - name: Run Android Integration Tests
      #   run: ./integration_android.sh

  merge-main-branch:
    runs-on: ubuntu-latest
    needs: flutter-integration-tests
    steps:
      - name: Get Repository
        uses: actions/checkout@v3

      - name: Git Merge div -> main
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout main
          git pull
          git merge dev
          git push
