name: Flutter Tests and Merge Main Branch
on:
  push:
    branches:
      - dev

jobs:
  flutter-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Run Unit and Widget tests
        run: flutter test test

  flutter-integration-tests:
    runs-on: ubuntu-latest
    needs: flutter-tests
    steps:
      - name: Get Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Run Android Integration Tests
        run: ./integration_android.sh

  merge-main-branch:
    runs-on: ubuntu-latest
    needs: flutter-integration-tests
    steps:
      - name: Get Repository
        uses: actions/checkout@v3

      - name: Merge dev -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: main
          github_token: ${{ github.token }}
